### ISSUE TITLE
Invalid list operator

### ISSUE THREAD

**Issue by dadepo** [thiagolvlsantos/json-predicate#10]
After upgrade to the 0.0.8 I do get the following exception now within the application where json-predicate is being used

```
Caused by: io.github.thiagolvlsantos.json.predicate.exceptions.JsonPredicateException: Invalid list operator: $and for {"$and":[{"Feature":{"$eq":"OTHE"}}]}
at io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson.read(PredicateFactoryJson.java:47) ~[json-predicate-0.0.8.jar!/:na]
at io.github.thiagolvlsantos.json.predicate.impl.PredicateDeserializer.deserialize(PredicateDeserializer.java:39) ~[json-predicate-0.0.8.jar!/:na]
... 59 common frames omitted
```

**Comment by thiagolvlsantos** [comment]
Hi @dadepo, I have some tests cases where It looks ok, i.e. https://github.com/thiagolvlsantos/json-predicate/blob/38d9be89cd6b928e7ff7a4b6c946af72972631cb/src/test/java/io/github/thiagolvlsantos/json/predicate/JsonPredicateTest.java#L89

Maybe the error message is not clear enougth, i.e. the "attribute 'Feature' could not be found" (because of the 'F' capital letter) or something like It.

Could you provide the example in a form of test?

Best regards.

**Comment by dadepo** [comment]
Thanks for checking. I'll get back to this before end of the week and see how to provide reproduction steps.

**Comment by thiagolvlsantos** [comment]
Hi, a tested again with a client project with the following code:
```
package test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import io.github.thiagolvlsantos.json.predicate.IPredicateFactory;
import io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson;

public class MainTest {

	public static void main(String[] args) throws Exception {
		IPredicateFactory factory = new PredicateFactoryJson();

		String filter = "{\"$and\":[{\"name\":{\"$eq\":\"alpha\"}}]}";
		Predicate<Object> p = factory.read(filter.getBytes());
		
		List<Object> projects = new ArrayList<Object>();
		Map<String,Object> map = new HashMap<String,Object>();
		map.put("name", "alpha");
		projects.add(map);
		map = new HashMap<String,Object>();
		map.put("name", "beta");
		projects.add(map);
		map = new HashMap<String,Object>();
		map.put("name", "gama");
		projects.add(map);
		
		List<Object> collect = projects.stream().filter(p).collect(Collectors.toList());
		System.out.println("SIZE:"+collect.size());
		System.out.println("is ALPHA:"+((Map<String,Object>)collect.get(0)).get("name").equals("alpha"));

		projects = new ArrayList<Object>();
		projects.add(new NamedObject("alpha"));
		projects.add(new NamedObject("beta"));
		projects.add(new NamedObject("gama"));
		
		filter = "{\"$and\":[{\"name\":{\"$eq\":\"beta\"}}]}";
		p = factory.read(filter.getBytes());

		collect = projects.stream().filter(p).collect(Collectors.toList());
		System.out.println("SIZE:"+collect.size());
		System.out.println("is BETA:"+((NamedObject)collect.get(0)).getName().equals("beta"));

		filter = "{\"$and\":[{\"name\":{\"$eq\":\"zeta\"}}]}";
		p = factory.read(filter.getBytes());

		collect = projects.stream().filter(p).collect(Collectors.toList());
		System.out.println("SIZE:"+collect.size());
}
	
	public static class NamedObject {
		private String name;

		public NamedObject(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}
}
```

The result was the expected:
```
23:09:26.001 [main] INFO io.github.thiagolvlsantos.json.predicate.impl.PredicateManagerDefault -- OPS:{$notmemberof=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $nmemberof=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $nmo=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $nin=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $!memberof=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $!mo=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $!in=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMemberOf, $lowerthan=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLower, $lt=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLower, $<=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLower, $match=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMatch, $m=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMatch, $regex=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMatch, $greaterthanequals=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreaterEquals, $greaterequalsthan=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreaterEquals, $ge=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreaterEquals, $gte=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreaterEquals, $>==class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreaterEquals, $equals=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateEquals, $eq=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateEquals, $===class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateEquals, $or=class io.github.thiagolvlsantos.json.predicate.array.impl.PredicateOr, $|=class io.github.thiagolvlsantos.json.predicate.array.impl.PredicateOr, $contains=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateContains, $c=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateContains, $memberof=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMemberOf, $mo=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMemberOf, $in=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateMemberOf, $lowerthanequals=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLowerEquals, $lowerequalsthan=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLowerEquals, $le=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLowerEquals, $lte=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLowerEquals, $<==class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateLowerEquals, $notmatch=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $nmatch=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $nm=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $nregex=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $!match=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $!m=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $!regex=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotMatch, $greaterthan=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreater, $gt=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreater, $>=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateGreater, $and=class io.github.thiagolvlsantos.json.predicate.array.impl.PredicateAnd, $&=class io.github.thiagolvlsantos.json.predicate.array.impl.PredicateAnd, $notequals=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotEquals, $ne=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotEquals, $!==class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotEquals, $not=class io.github.thiagolvlsantos.json.predicate.wrapper.impl.PredicateNot, $!=class io.github.thiagolvlsantos.json.predicate.wrapper.impl.PredicateNot, $notcontains=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotContains, $ncontains=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotContains, $nc=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotContains, $!contains=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotContains, $!c=class io.github.thiagolvlsantos.json.predicate.value.impl.PredicateNotContains}
23:09:26.088 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 	 LIST>PredicateAnd  $and: [{"name":{"$eq":"alpha"}}]
23:09:26.114 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 		 VALUE>PredicateEquals name: {"$eq":"alpha"}
SIZE:1
is ALPHA:true
23:09:26.123 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 	 LIST>PredicateAnd  $and: [{"name":{"$eq":"beta"}}]
23:09:26.123 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 		 VALUE>PredicateEquals name: {"$eq":"beta"}
SIZE:1
is BETA:true
23:09:26.281 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 	 LIST>PredicateAnd  $and: [{"name":{"$eq":"zeta"}}]
23:09:26.281 [main] DEBUG io.github.thiagolvlsantos.json.predicate.impl.PredicateFactoryJson -- 		 VALUE>PredicateEquals name: {"$eq":"zeta"}
SIZE:0
```

[]'s

**Comment by dadepo** [comment]
Unfortunately I have not had the time to try to reproduce this. The only thing I noticed was that the error with the new version shows up when I deploy the app in docker, but running the same locally did not. So it might be related to dependency resolution. I'll close this for now, when I get around to it, and I could reproduce it., I'll reopen the issue.
