### ISSUE TITLE
"(" causes IllegalArgumentException Indexed or mapped properties are not supported on objects

### ISSUE THREAD

**Issue by dadepo** [thiagolvlsantos/json-predicate#9]
If "(" is present in the field name, then using the filter throws. 

A minimal code to reproduce this issue

```
  public static void main(String[] args) {
    IPredicateFactory factory = new PredicateFactoryJson();

    String filter = "{\"p(et\":{\"$contains\": \"cat\"}}";
    Predicate<Object> p = factory.read(filter.getBytes());

    List<Map<String, String>> projects = List.of(Map.of("p(et", "cat"));
    System.out.println(projects.stream().filter(p).collect(Collectors.toList()));
  }
```

This would throw with the following stack trace

```
Exception in thread "main" java.lang.IllegalArgumentException: Indexed or mapped properties are not supported on objects of type Map: p(e)
	at org.apache.commons.beanutils.PropertyUtilsBean.getPropertyOfMapBean(PropertyUtilsBean.java:852)
	at org.apache.commons.beanutils.PropertyUtilsBean.getNestedProperty(PropertyUtilsBean.java:785)
	at org.apache.commons.beanutils.PropertyUtilsBean.getProperty(PropertyUtilsBean.java:885)
	at org.apache.commons.beanutils.PropertyUtils.getProperty(PropertyUtils.java:464)
	at io.github.thiagolvlsantos.json.predicate.impl.AccessDefault.get(AccessDefault.java:16)
	at io.github.thiagolvlsantos.json.predicate.value.AbstractPredicateValue.unwrapp(AbstractPredicateValue.java:20)
	at io.github.thiagolvlsantos.json.predicate.value.impl.PredicateContains.test(PredicateContains.java:16)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
```

This is with the `0.0.7` version of the library.

Interesting enough, having any other special characters in the field name, for example `<, |, etc and even )` works fine.

**Comment by dadepo** [comment]
This issue seems to have been fixed in the `0.0.8-SNAPSHOT` version. Unfortunately this has not been published to the maven repository yet.

@thiagolvlsantos apologies for the bother, is there anything preventing publishing 0.0.8-SNAPSHOT? Is there anything I can do to help?

**Comment by thiagolvlsantos** [comment]
Hi @dadepo, sorry for taking too long to answer, I was on vacations.

Tomorow I'll check and release the closed version 0.0.8, and see if the following snapshot version is being released as expected.

As soon as I publish I'll close this issue.

**Comment by dadepo** [comment]
Hi @thiagolvlsantos apologies for the bother, any updates regarding publishing the next version? Any way I can be of help?

**Comment by thiagolvlsantos** [comment]
Hi @dadepo, my apologies for taking too long. The GPG certificate has expired acording to my last try a few days ago (check actions). Working on replacement.

Unfortunally I'm running out of time to fix it, a knee injurry requires me a lot o time on diagnostics. I'll try fix certificate late today.

Thanks for your help offer, but in this case I have to manage a time for it.

Best regards, Thiago

**Comment by thiagolvlsantos** [comment]
Hi @dadepo, 

I managed to correct the actions/secrets and a version 0.0.8-SNAPSHOT is already available on Maven repository https://s01.oss.sonatype.org/#nexus-search;quick~json-predicate.

In a few hours I migth publish the release version. I'll get the chance to deploy releases of every lib project I have, specially those which depends on json-predicate.

Once again, sorry for the time taken and thanks for your interest, that make me resume funny times on Github.

Keeping it open until 0.0.8 is on Maven repository. 

Best regards, Thiago.

**Comment by thiagolvlsantos** [comment]
Hi @dadepo, release 0.0.8 done. []'s
